apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/woodchat/ops-manifests
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: llm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
