# llm-service-rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: llm-service
  namespace: llm
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: llm-service
      previewService: llm-service-preview
      autoPromotionEnabled: true
  selector:
    matchLabels:
      app: llm-service
  template:
    metadata:
      labels:
        app: llm-service
    spec:
      containers:
        - name: llm-service
          image: shubhbuz/ops-service:5f7a6bc763071467be39d4f4622b0fa984cf5f0b
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: llm
spec:
  selector:
    app: llm-service
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service-preview
  namespace: llm
spec:
  selector:
    app: llm-service
  ports:
    - port: 80
      targetPort: 8000
