# prometheus-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: llm
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'llm-service'
        static_configs:
          - targets: ['llm-service:80']
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s

      - job_name: 'ollama'
        static_configs:
          - targets: ['ollama:11434']
        metrics_path: '/metrics'
        scrape_interval: 30s
        scrape_timeout: 10s
