apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: llm
spec:
  selector:
    app: llm-service
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service-preview
  namespace: llm
spec:
  selector:
    app: llm-service
  ports:
    - port: 80
      targetPort: 8000
